# Python para Dados - Atividade de Fixação Numpy
[Link da aula](https://www.maismulheres.tech/courses/take/turma-6-bootcamp-data-analytics/pdfs/52281725-atividades-numpy)

## Introdutório

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [42]:
import numpy as np

#### 1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.

In [9]:
array1 = np.random.random((4, 3))
array1

array([[0.0055215 , 0.93391626, 0.51561687],
       [0.70256336, 0.14882572, 0.5806659 ],
       [0.63278599, 0.699132  , 0.27065177],
       [0.4482313 , 0.31734118, 0.03077411]])

#### 2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios

In [10]:
array2 = np.random.randint(0, 100, size=(3, 5))
array2

array([[13, 23,  8, 68, 10],
       [17, 11, 74,  6, 15],
       [98, 50, 95, 74, 79]])

#### 3. Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [11]:
array3 = np.zeros((10, 5))
array3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Crie um array que vá entre 0 e 90, pulando de 4 em 4

In [12]:
array4 = np.arange(0, 91, 4)
array4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

#### 5. Reduza o array (5, 7) a apenas uma dimensão

In [13]:
array5 = np.random.random((5, 7))
array5_flat = array5.flatten()
array5_flat

array([0.98972826, 0.89109393, 0.13010076, 0.81784001, 0.09561772,
       0.98600436, 0.16018409, 0.99810638, 0.64699426, 0.85597069,
       0.58624689, 0.68248703, 0.68088352, 0.31107228, 0.89717762,
       0.92391844, 0.07214423, 0.37768207, 0.62252017, 0.63202398,
       0.04964939, 0.9739533 , 0.16032038, 0.73909062, 0.26528516,
       0.52340901, 0.54999517, 0.15537528, 0.46455972, 0.96733121,
       0.285744  , 0.49973616, 0.08164801, 0.62492292, 0.8530298 ])

#### 6. Crie um array que representa a cartilha do jogo de bingo
#####   Cada cartela tem 12 números variando de 1 a 30, e há 10 participantes

In [17]:
cartelas = np.random.randint(1, 31, size=(10, 4, 3))
cartelas

array([[[23, 16, 10],
        [24, 20,  1],
        [ 6,  3, 21],
        [21,  1, 29]],

       [[ 9, 27, 27],
        [28,  9, 24],
        [ 2,  9, 17],
        [ 5, 21,  8]],

       [[ 4, 11, 29],
        [17, 14, 13],
        [ 8, 27, 25],
        [ 2,  8, 27]],

       [[ 6, 24, 18],
        [ 4, 22, 25],
        [ 2, 28, 16],
        [11, 17, 21]],

       [[ 5,  7, 29],
        [29, 27, 24],
        [10, 14, 30],
        [20, 26, 24]],

       [[19,  7, 27],
        [10, 24,  3],
        [12, 11,  8],
        [25,  7, 14]],

       [[17,  5, 15],
        [12, 22, 12],
        [11, 18,  7],
        [ 7, 15, 22]],

       [[22, 23,  2],
        [23,  3, 18],
        [21, 30,  4],
        [19, 14,  3]],

       [[ 9,  7, 12],
        [11, 26, 16],
        [ 2, 12, 22],
        [19, 23, 19]],

       [[25, 25, 26],
        [22, 12, 20],
        [20, 25, 28],
        [19, 15, 15]]])

#### 7. Faça reshapes das cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [15]:
cartelas_reshaped = cartelas.reshape((5, 4, 6))
cartelas_reshaped

array([[[ 7,  7, 27, 24,  9,  7],
        [ 4,  4, 15, 27, 27, 11],
        [ 4, 30, 19, 19,  2, 26],
        [22,  6, 20,  3, 20, 24]],

       [[21,  6, 30, 20, 27, 17],
        [ 1, 21, 27, 28,  2,  3],
        [29, 14, 26, 20, 16, 24],
        [26, 24,  3,  3, 23, 13]],

       [[14,  6, 13, 13, 17, 11],
        [18,  8,  2,  8,  9, 12],
        [19, 20, 26, 28,  9, 26],
        [25, 29, 20, 11, 19, 18]],

       [[ 2, 16, 23, 23, 23,  3],
        [14, 24,  3, 11, 10, 22],
        [ 7, 26, 13, 17, 20,  1],
        [ 4, 30, 13, 24, 28, 14]],

       [[ 3,  9, 30, 20, 29, 27],
        [18, 27, 17, 22, 16, 13],
        [15,  4, 16, 28,  4, 17],
        [21, 20, 25, 16, 28, 14]]])

## Manipulando Arrays

### 1.Explorando Ecossistemas:
Como bióloga marinha,me encontrei em uma expedição nas profundezas do Oceano Pacífico,onde estávamos estudando a biodiversidade e a saúde dos recifes de coral.O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

- ID da espécie
- Quantidade de representantes encontrados
- Profundeza
- Tamanho médio da espécie

In [3]:
# Dados

especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

#### a. Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies


In [7]:
qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

#### b. De qtd_especies selecione apenas as primeiras 3 quantidades e print

In [9]:
print(qtd_especies[0:3])

[ 89 123  22]


#### c. Print as 5 últimas quantidades de espécies

In [14]:
print(qtd_especies[-5:])  #É só colocar a quantidade e o negativo

[ 64  84 105 103 124]


#### d. Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente

In [28]:
tamanho = np.sort(especies[:, 3])
tamanho

# np.sort(especies[:, 3])[::-1] #caso queira decrescente

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

### 2. Ainda usando o Array de espécies marítimas:

#### a. Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22

In [29]:
especies

array([[747,  89,  33,   1],
       [623, 123,  32,   2],
       [501,  22,  49,   5],
       [116, 101,  42,   5],
       [297,  56,  69,   7],
       [613,  64,  27,  10],
       [295,  84,  29,  13],
       [692, 105,  72,  14],
       [229, 103,  35,  16],
       [374, 124,  70,  22]])

In [32]:
maior_especies = especies[:, 3] == 22 #para me retornar apenas a linha da espécie 22
maior_especies

array([False, False, False, False, False, False, False, False, False,
        True])

#### b. Usando fency index faça um array que contém apenas dados da espécie com ID 297

In [35]:
mask_297 = especies[:,0] == 297
especies[mask_297]

array([[297,  56,  69,   7]])


#### c. Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados

In [37]:
especie_105 = np.where(especies[:,1] == 105)
especies[especie_105]

array([[692, 105,  72,  14]])

#### d. Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo"

In [40]:
mask_60 = np.where(especies[:,2] > 60, "Profundo", especies[:,2])
mask_60

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

### 3. Ainda no conjunto 'especies':
#### a. Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]

In [44]:
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
novas_especies

array([[204,  10,  40,  12],
       [392,  11,  81,  11]])

In [45]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   1],
       [623, 123,  32,   2],
       [501,  22,  49,   5],
       [116, 101,  42,   5],
       [297,  56,  69,   7],
       [613,  64,  27,  10],
       [295,  84,  29,  13],
       [692, 105,  72,  14],
       [229, 103,  35,  16],
       [374, 124,  70,  22],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

#### b. Adicione mais uma coluna na no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]

In [47]:
ver = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1]).reshape((10,1))
ver

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [50]:
np.concatenate((especies, ver), axis = 1)

array([[747,  89,  33,   1,   0],
       [623, 123,  32,   2,   1],
       [501,  22,  49,   5,   0],
       [116, 101,  42,   5,   0],
       [297,  56,  69,   7,   0],
       [613,  64,  27,  10,   0],
       [295,  84,  29,  13,   1],
       [692, 105,  72,  14,   0],
       [229, 103,  35,  16,   1],
       [374, 124,  70,  22,   1]])

## Cálculo com Array


In [ ]:
# Dados
acidentes = np.array([[1, 3, 2],
                    [0, 1, 0],
                    [2, 1, 4],
                    [0, 0, 0],
                    [1, 1, 0]])

#### a. O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.


#### b. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

#### c. Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que seja feita essa operação.


#### d. A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos apresentados durante o semestre. Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores: 1, 2, 1.