In [3]:
import numpy as np

In [ ]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

4

In [ ]:
arr[0]

2

In [ ]:
cartela_bingo = np.array([[16, 10,  3, 15],
                            [14, 23, 17, 27],
                            [ 6, 19,  3,  1],
                            [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [ ]:
cartela_bingo[:, 1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [ ]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [ ]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [ ]:
np.sort(cartela_bingo, axis=0)

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

## Filtrando Arrays

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

### Máscara em array 2d

In [4]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [5]:
pessoas_id_idade[:,1] % 2 == 0  #Quais são os valores divisíveis por 2

array([ True, False, False,  True])

In [11]:
mask_maior21 = pessoas_id_idade[:,1] > 21
mask_maior21

array([ True, False,  True,  True])

In [12]:
pessoas_id_idade[mask_maior21] #mostram quem são

array([[ 1, 22],
       [ 3, 27],
       [ 4, 26]])

In [13]:
np.where(mask_maior21) #Mostra que ta na linha 0,2 e 3

(array([0, 2, 3], dtype=int64),)

In [14]:
np.where(pessoas_id_idade > 21, "maior idade", pessoas_id_idade)

array([['1', 'maior idade'],
       ['2', '21'],
       ['3', 'maior idade'],
       ['4', 'maior idade']], dtype='<U11')

### Fancy indexing

In [7]:
cartela_bingo = np.array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [8]:
np.where(cartela_bingo % 3 == 0 ) #Mostra quem são os divisíveis por 3

(array([0, 0, 1, 2, 2, 3], dtype=int64),
 array([2, 3, 3, 0, 2, 2], dtype=int64))

In [9]:
np.where(cartela_bingo % 3 == 0, "", cartela_bingo) #Coloca "" onde tem numero divisível por 3 na cartela

array([['16', '10', '', ''],
       ['14', '23', '17', ''],
       ['', '19', '', '1'],
       ['10', '4', '', '19']], dtype='<U11')

# Adicionando e removendo dados do Array
## Concatenando linhas

In [15]:
arrv1 = np.random.randint(10, size=(3,2))
arrv1

array([[3, 3],
       [5, 4],
       [2, 4]])

In [16]:
arrv2 = np.array([["Peras", "Morangos"]])
arrv2

array([['Peras', 'Morangos']], dtype='<U8')

In [17]:
np.concatenate((arrv1, arrv2))

array([['3', '3'],
       ['5', '4'],
       ['2', '4'],
       ['Peras', 'Morangos']], dtype='<U11')

## Concatenando colunas

In [18]:
arro1 = np.array(["Uva", "Abacaxi", "Maça"]).reshape((3,1))
arro1
#Necessário reshape para nao ficar (3,)

array([['Uva'],
       ['Abacaxi'],
       ['Maça']], dtype='<U7')

In [19]:
conc = np.concatenate((arrv1, arro1), axis = 1) #indica coluna

array([['3', '3', 'Uva'],
       ['5', '4', 'Abacaxi'],
       ['2', '4', 'Maça']], dtype='<U11')

### Deletando

In [ ]:
np.delete(conc, 1, axis=0) #vai deletar a segunda linha 

## Cálculos com Array

In [20]:
# Dados
acidentes = np.array([[1, 3, 2],
                    [0, 1, 0],
                    [2, 1, 4],
                    [0, 0, 0],
                    [1, 1, 0]])

### Soma 

In [21]:
acidentes.sum() #soma tudo

16

In [22]:
acidentes.sum(axis = 1) #soma colunas

array([6, 1, 7, 0, 2])

In [ ]:
acidentes.cumsum(axis=1) #soma cumulativa

### Mínimos e máximos

In [ ]:
acidentes.min()
acidentes.max(axis=0)

### Média

In [ ]:
acidentes.mean()
acidentes.mean(axis=1, keepdms=True) #Mantém dimensão

## Operações com vetorização


In [24]:
arr = np.array([[1,2], [4,5]])
arr +=3 # para add 3 a em cada valor
arr

array([[4, 5],
       [7, 8]])

In [25]:
arr *5 #fazer multiplicado por 5

array([[20, 25],
       [35, 40]])