# Python para Dados - Atividade de Fixação Numpy
[Link da aula](https://www.maismulheres.tech/courses/take/turma-6-bootcamp-data-analytics/pdfs/52281725-atividades-numpy)

## Introdutório

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

In [9]:
# 1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.
array1 = np.random.random((4, 3))
array1

array([[0.0055215 , 0.93391626, 0.51561687],
       [0.70256336, 0.14882572, 0.5806659 ],
       [0.63278599, 0.699132  , 0.27065177],
       [0.4482313 , 0.31734118, 0.03077411]])

In [10]:
# 2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.
array2 = np.random.randint(0, 100, size=(3, 5))
array2

array([[13, 23,  8, 68, 10],
       [17, 11, 74,  6, 15],
       [98, 50, 95, 74, 79]])

In [11]:
# 3. Crie um array com 5 colunas e 10 linhas inicializados com zeros.
array3 = np.zeros((10, 5))
array3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# 4. Crie um array que vá entre 0 e 90, pulando de 4 em 4.
array4 = np.arange(0, 91, 4)
array4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

In [13]:
# 5. Reduza o array (5, 7) a apenas uma dimensão.
array5 = np.random.random((5, 7))
array5_flat = array5.flatten()
array5_flat

array([0.98972826, 0.89109393, 0.13010076, 0.81784001, 0.09561772,
       0.98600436, 0.16018409, 0.99810638, 0.64699426, 0.85597069,
       0.58624689, 0.68248703, 0.68088352, 0.31107228, 0.89717762,
       0.92391844, 0.07214423, 0.37768207, 0.62252017, 0.63202398,
       0.04964939, 0.9739533 , 0.16032038, 0.73909062, 0.26528516,
       0.52340901, 0.54999517, 0.15537528, 0.46455972, 0.96733121,
       0.285744  , 0.49973616, 0.08164801, 0.62492292, 0.8530298 ])

In [14]:
# 6. Crie um array que representa a cartilha do jogo de bingo.
#    Cada cartela tem 12 números variando de 1 a 30, e há 10 participantes.
cartelas = np.random.choice(np.arange(1, 31), size=(10, 4, 3), replace=True)
cartelas

array([[[ 7,  7, 27],
        [24,  9,  7],
        [ 4,  4, 15],
        [27, 27, 11]],

       [[ 4, 30, 19],
        [19,  2, 26],
        [22,  6, 20],
        [ 3, 20, 24]],

       [[21,  6, 30],
        [20, 27, 17],
        [ 1, 21, 27],
        [28,  2,  3]],

       [[29, 14, 26],
        [20, 16, 24],
        [26, 24,  3],
        [ 3, 23, 13]],

       [[14,  6, 13],
        [13, 17, 11],
        [18,  8,  2],
        [ 8,  9, 12]],

       [[19, 20, 26],
        [28,  9, 26],
        [25, 29, 20],
        [11, 19, 18]],

       [[ 2, 16, 23],
        [23, 23,  3],
        [14, 24,  3],
        [11, 10, 22]],

       [[ 7, 26, 13],
        [17, 20,  1],
        [ 4, 30, 13],
        [24, 28, 14]],

       [[ 3,  9, 30],
        [20, 29, 27],
        [18, 27, 17],
        [22, 16, 13]],

       [[15,  4, 16],
        [28,  4, 17],
        [21, 20, 25],
        [16, 28, 14]]])

In [15]:
# 7. Faça reshapes das cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.
cartelas_reshaped = cartelas.reshape((5, 4, 6))
cartelas_reshaped

array([[[ 7,  7, 27, 24,  9,  7],
        [ 4,  4, 15, 27, 27, 11],
        [ 4, 30, 19, 19,  2, 26],
        [22,  6, 20,  3, 20, 24]],

       [[21,  6, 30, 20, 27, 17],
        [ 1, 21, 27, 28,  2,  3],
        [29, 14, 26, 20, 16, 24],
        [26, 24,  3,  3, 23, 13]],

       [[14,  6, 13, 13, 17, 11],
        [18,  8,  2,  8,  9, 12],
        [19, 20, 26, 28,  9, 26],
        [25, 29, 20, 11, 19, 18]],

       [[ 2, 16, 23, 23, 23,  3],
        [14, 24,  3, 11, 10, 22],
        [ 7, 26, 13, 17, 20,  1],
        [ 4, 30, 13, 24, 28, 14]],

       [[ 3,  9, 30, 20, 29, 27],
        [18, 27, 17, 22, 16, 13],
        [15,  4, 16, 28,  4, 17],
        [21, 20, 25, 16, 28, 14]]])

## Manipulando Arrays

**1.Explorando Ecossistemas:** Como bióloga marinha,me encontrei em uma expedição nas profundezas do Oceano Pacífico,onde estávamos estudando a biodiversidade e a saúde dos recifes de coral.O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

- ID da espécie
- Quantidade de representantes encontrados
- Profundeza
- Tamanho médio da espécie